### ISSUE TITLE
老哥，我想问一下，这个代码的训练出来的模型，怎么样在官方版centernet使用？

### ISSUE THREAD

**Issue by idantony** [GNAYUOHZ/centernet-visdrone#1]
您好，我是一个初学者，正如题目所说，我在结合您这个代码和官方版https://github.com/xingyizhou/CenterNet 一起在看代码学习，我用您这个跑出来的模型，想试试在官方版里试试推论，但是参数和代码不知道怎么改，请多多指教！

**Comment by GNAYUOHZ** [comment]
你好，网络不是完全一样的，不能通用的

**Comment by zubi00** [comment]
I am using your code "[https://github.com/GNAYUOHZ/centernet-visdrone]" for object detection only to train in my own dataset. I changed the code where necessary but after training, I always encounter the same error as shown below. Hope you will consider my request.
evaluating object category 1/10...
evaluating object category 2/10...
evaluating object category 3/10...
evaluating object category 4/10...
Evaluation completed. The performance of the detector is presented as follows.
2022-06-23 08:32:56: AP [IoU=0.50:0.95 | maxDets=500] = 11.79%.
2022-06-23 08:32:56: AP [IoU=0.50      | maxDets=500] = 19.20%.
2022-06-23 08:32:56: AP [IoU=0.75      | maxDets=500] = 13.12%.
2022-06-23 08:32:56: AR [IoU=0.50:0.95 | maxDets=  1] = 3.39%.
2022-06-23 08:32:56: AR [IoU=0.50:0.95 | maxDets= 10] = 8.80%.
2022-06-23 08:32:56: AR [IoU=0.50:0.95 | maxDets=100] = 13.54%.
2022-06-23 08:32:56: AR [IoU=0.50:0.95 | maxDets=500] = 27.67%.
2022-06-23 08:32:56: Class Car AP = 10.82%
2022-06-23 08:32:56: Class Truck AP = 13.81%
2022-06-23 08:32:56: Class Stop-Sign AP = 19.76%
2022-06-23 08:32:56: Class Traffic-Light AP = 0.63%
Traceback (most recent call last):
  File "C:\centernet-motive\test.py", line 130, in <module>
    test_visdrone()
  File "C:\centernet-motive\test.py", line 112, in test_visdrone
    f'Class {opt.dataset_info["class_name"][i]} AP = {ap:3.2f}%')
IndexError: list index out of range
