### ISSUE TITLE
1 class training

### ISSUE THREAD

**Issue by HenryKang1** [GNAYUOHZ/centernet-visdrone#2]
Hello. I am wondering that I am trying to train the 1 class object detection using your code.
And then there is error bout 
for iter_id, batch in enumerate(train_loader):
Exception has occurred: IndexError
Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/henry/miniconda3/envs/flowtorch/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/henry/miniconda3/envs/flowtorch/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/henry/miniconda3/envs/flowtorch/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "[/home/henry/centernet-visdrone/src/dataset.py]()", line 185, in __getitem__
    np.maximum(gs_mask, hm[i], out=gs_mask)
IndexError: index 1 is out of bounds for axis 0 with size 1
  File "/home/henry/centernet-visdrone/src/dataset.py", line 205, in <module>
    for iter_id, batch in enumerate(train_loader):

any suggestion?

**Comment by HenryKang1** [comment]
I solve the problem.
The issue comes from 
line 185 Since I deal with 1 class I turn off the loop.
